-- Who is allowed to go quiet, and who has.
--
-- The alert sound was a per-device preference and nothing more: anybody could turn it
-- off, nobody could see that they had, and a tablet sitting silently in the plant room
-- looked exactly like a tablet that was listening. For a department where the whole point
-- of assigning a P1 is that somebody hears about it, that is a hole.
--
-- Two halves. The permission decides who may silence their own alerts at all. The table
-- records what each device is actually doing, so a supervisor can see a technician who is
-- unreachable rather than discovering it during an outage.

INSERT OR IGNORE INTO permissions (code, module, description)
VALUES ('alerts.silence', 'core', 'Turn their own alert sounds off');

-- Granted to everybody who is not handed work. A technician or team lead is assigned jobs
-- and is expected to hear them; a supervisor sits in meetings, a finance officer works in
-- a quiet office, and neither is waiting to be dispatched.
--
-- Deliberately a grant and not a hard-coded rule: a property that runs differently can
-- change it under Admin > Roles like any other permission, which is the whole premise of
-- this system's permission model.
INSERT OR IGNORE INTO role_permissions (role_id, permission_code, scope)
SELECT r.id, 'alerts.silence', 'all'
  FROM roles r
 WHERE r.key NOT IN ('technician', 'team_lead');

-- One row per account per device, because the setting is per device: the same technician
-- may have a phone that chimes and a desk browser that does not, and both facts matter.
CREATE TABLE alert_state (
  id           TEXT PRIMARY KEY,
  property_id  TEXT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
  user_id      TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- Generated by the browser and kept in its local storage. Not an identifier of a
  -- person or a machine — only a way to tell one browser from another so two devices do
  -- not overwrite each other's row.
  device_id    TEXT NOT NULL,
  -- What the person has chosen.
  sound_on     INTEGER NOT NULL DEFAULT 1 CHECK (sound_on IN (0,1)),
  -- Whether the browser is actually able to play it. A page that has not been touched
  -- since it loaded cannot make a sound at all, whatever the setting says — so a device
  -- can be set to alert and still be silent, and a supervisor needs to see that
  -- difference rather than assume the toggle tells the whole story.
  audio_ready  INTEGER NOT NULL DEFAULT 0 CHECK (audio_ready IN (0,1)),
  user_agent   TEXT,
  last_seen_at TEXT NOT NULL,
  created_at   TEXT NOT NULL,
  UNIQUE (user_id, device_id)
);

CREATE INDEX idx_alert_state_property ON alert_state(property_id, last_seen_at DESC);
