import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { requireSignedIn } from '../auth/guard.js';
import { ulid } from '../lib/ids.js';
import * as bus from '../services/bus.js';
import * as devices from '../services/devices.js';
import { audit } from '../audit.js';
import { nowIso } from '../lib/time.js';
import { networkView } from '../services/network.js';
import { readHostFile } from '../config.js';

/** `localhost:4700`, `127.0.0.1`, `[::1]:5173` — any address that only means "this PC". */
function isLoopback(hostHeader: string): boolean {
  const name = hostHeader.replace(/:\d+$/, '').replace(/^\[|\]$/g, '').toLowerCase();
  return name === 'localhost' || name === '::1' || name.startsWith('127.');
}

export async function meRoutes(app: FastifyInstance): Promise<void> {
  /**
   * Ask for a code to pair a phone with.
   *
   * Generated by the person themselves from a browser where they are already signed in,
   * which is what makes the whole flow safe: the code inherits the identity of the
   * session that asked for it, so nobody can mint a token for an account they cannot
   * already use.
   */
  app.post('/api/me/pairing-code', { preHandler: requireSignedIn() }, async (req) => {
    const me = req.principal!;
    // Whatever address this browser reached the host on is the one the phone can reach it
    // on too — they are on the same wifi. Guessing an address here instead would be how
    // the QR code ends up pointing at an adapter nothing can see.
    const proto = (req.headers['x-forwarded-proto'] as string) ?? req.protocol;
    const host = req.headers.host ?? '';
    let baseUrl = `${proto}://${host}`;

    /*
     * Except when that address is this PC talking to itself.
     *
     * Somebody pairing from the host PC's own browser reached it as `localhost`, and a
     * phone that dials `localhost` dials itself — the scan "does nothing" while the app
     * waits on a connection that can never answer. Hand out the address the Host PC tab
     * would, on the plain HTTP port every phone can reach.
     */
    if (isLoopback(host)) {
      const view = await networkView(readHostFile(app.config.dataDir).advertise ?? null);
      if (view.advertise) baseUrl = `http://${view.advertise}:${app.config.port}`;
    }

    const code = devices.createPairingCode(app.db, me.propertyId, me.userId, baseUrl);
    return code;
  });

  /**
   * Redeem it. The one route a phone may call before it has a token.
   *
   * Rate-limited by the code's own shape rather than by the caller: eight characters from
   * a 32-letter alphabet, single use, ten minutes. Guessing one inside its life is not a
   * strategy, and a wrong guess tells the caller nothing it did not already know.
   */
  app.post('/api/devices/pair', async (req, reply) => {
    const body = z.object({
      code: z.string().min(4).max(32),
      deviceName: z.string().min(1).max(60),
      platform: z.enum(['android', 'ios', 'other']).default('android'),
      appVersion: z.string().max(30).optional(),
    }).safeParse(req.body);
    if (!body.success) return reply.code(400).send({ error: 'invalid', issues: body.error.issues });

    const d = body.data;
    const paired = devices.redeemPairingCode(
      app.db, d.code, d.deviceName, d.platform, d.appVersion);

    audit(app.db, {
      propertyId: req.principal?.propertyId ?? '',
      userId: paired.user.id, actorName: paired.user.displayName,
      action: 'device.paired', entityType: 'device', entityId: paired.deviceId,
      after: { name: d.deviceName, platform: d.platform }, ip: req.ip,
    });
    return reply.code(201).send(paired);
  });

  /** The phones this person has paired, and a way to let one go. */
  app.get('/api/me/devices', { preHandler: requireSignedIn() }, async (req) => ({
    devices: devices.listForUser(app.db, req.principal!.userId),
  }));

  app.delete('/api/me/devices/:id', { preHandler: requireSignedIn() }, async (req, reply) => {
    const me = req.principal!;
    const id = (req.params as { id: string }).id;
    // Scoped to this person's own devices: a path parameter must never be a way to
    // silence somebody else's phone.
    const mine = devices.listForUser(app.db, me.userId).some((d) => d.id === id);
    if (!mine) return reply.code(404).send({ error: 'not_found', message: 'That is not one of your devices.' });
    devices.revoke(app.db, me.propertyId, id, me.userId);
    audit(app.db, {
      propertyId: me.propertyId, userId: me.userId, actorName: me.displayName,
      action: 'device.revoked', entityType: 'device', entityId: id, ip: req.ip,
    });
    return { ok: true };
  });

  /**
   * The live connection.
   *
   * One open response per device, written to the moment something happens, instead of
   * every screen asking the same questions on a timer. On a LAN this is the right shape:
   * no broker, no polling, and a P1 lands on the phone in the plant room as fast as the
   * supervisor's finger leaves the button.
   *
   * Server-sent events rather than a websocket on purpose. The traffic is one-way, it is
   * plain HTTP so nothing in the building has to be reconfigured, and the browser
   * reconnects by itself when the wifi drops — which on a phone walking through a
   * basement is the normal case, not the exception.
   */
  app.get('/api/events', { preHandler: requireSignedIn() }, async (req, reply) => {
    const me = req.principal!;

    reply.raw.writeHead(200, {
      'content-type': 'text/event-stream',
      'cache-control': 'no-cache, no-transform',
      connection: 'keep-alive',
      // Nothing in this deployment proxies, but a department that later puts one in front
      // would otherwise see every alert buffered into silence.
      'x-accel-buffering': 'no',
    });

    const write = (e: { kind: string; at: string }): void => {
      reply.raw.write(`event: ${e.kind}\ndata: ${JSON.stringify(e)}\n\n`);
    };

    // Say hello immediately: the client treats the first line as proof the stream is
    // live, and falls back to polling if it never arrives.
    write({ kind: 'ping', at: nowIso() });

    const unsubscribe = bus.subscribe(me.userId, write);

    /*
     * A paired phone says so while it is here, and stops saying so the moment it is not.
     *
     * This is the column the supervisor's screen depends on, and the reason it is set
     * here rather than at pairing: Android manufacturers kill background services
     * whatever permissions you grant — Transsion phones most of all, which is most of the
     * handsets on a Nigerian property. You cannot stop that happening. What you can do is
     * make sure a human finds out before an outage does.
     */
    const device = req.deviceId;
    if (device) devices.setConnected(app.db, device, true);

    const done = (): void => {
      unsubscribe();
      if (device) devices.setConnected(app.db, device, false);
    };
    req.raw.on('close', done);
    req.raw.on('error', done);

    // Keeps fastify from treating the handler's return as the end of the response.
    return reply;
  });

  /**
   * Work that has been handed to this person and not yet picked up.
   *
   * The list the phone rings about. Computed here rather than inferred on the device
   * because the rule for "still waiting on you" belongs with the state machine, and
   * because a client guessing it would keep ringing about a job somebody else had
   * already taken.
   */
  app.get('/api/me/outstanding', { preHandler: requireSignedIn() }, async (req) => {
    const me = req.principal!;
    if (!me.staffId) return { unaccepted: [] };
    const rows = app.db.prepare(
      `SELECT w.id, w.ref, w.title, w.priority, w.assigned_at, w.respond_by
         FROM work_orders w
        WHERE w.property_id = ? AND w.assigned_to_staff_id = ? AND w.status = 'assigned'
        ORDER BY w.priority, w.assigned_at`
    ).all(me.propertyId, me.staffId) as {
      id: string; ref: string; title: string; priority: string;
      assigned_at: string | null; respond_by: string | null;
    }[];
    return { unaccepted: rows, at: nowIso() };
  });

  /**
   * What this device is doing about alerts.
   *
   * Reported by the browser rather than asked for, because the setting lives in that
   * browser's own storage and the server has no other way to know. Two separate facts
   * are recorded: what the person chose, and whether the browser is actually able to
   * make a sound — a page nobody has touched since it loaded cannot play audio at all,
   * whatever the toggle says, and a supervisor needs to see the difference rather than
   * assume a silent tablet is a listening one.
   */
  app.post('/api/me/alerts', { preHandler: requireSignedIn() }, async (req, reply) => {
    const body = z.object({
      deviceId: z.string().min(8).max(64),
      soundOn: z.boolean(),
      audioReady: z.boolean(),
    }).safeParse(req.body);
    if (!body.success) return reply.code(400).send({ error: 'invalid', issues: body.error.issues });

    const me = req.principal!;
    const at = nowIso();
    const d = body.data;
    // A role that may not silence its alerts is recorded as hearing them whatever the
    // browser says, so a stale value in local storage cannot misreport somebody.
    const maySilence = me.permissions.has('alerts.silence');
    const on = maySilence ? d.soundOn : true;

    app.db.prepare(
      `INSERT INTO alert_state (id, property_id, user_id, device_id, sound_on, audio_ready,
                                user_agent, last_seen_at, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
       ON CONFLICT (user_id, device_id) DO UPDATE SET
         sound_on = excluded.sound_on, audio_ready = excluded.audio_ready,
         user_agent = excluded.user_agent, last_seen_at = excluded.last_seen_at`
    ).run(ulid(), me.propertyId, me.userId, d.deviceId, on ? 1 : 0, d.audioReady ? 1 : 0,
          String(req.headers['user-agent'] ?? '').slice(0, 200), at, at);

    return { ok: true, maySilence: maySilence };
  });

  app.get('/api/me', { preHandler: requireSignedIn() }, async (req) => {
    const me = req.principal!;
    const property = app.db.prepare('SELECT name, short_name, timezone, currency FROM properties WHERE id = ?')
      .get(me.propertyId) as { name: string; short_name: string; timezone: string; currency: string } | undefined;
    return {
      user: {
        id: me.userId,
        username: me.username,
        displayName: me.displayName,
        staffId: me.staffId,
        role: me.roleKey,
        roleName: me.roleName,
        roleDescription: me.roleDescription,
        mustChangePassword: me.mustChangePassword,
      },
      property,
      permissions: [...me.permissions].sort(),
      scopes: me.scopes,
    };
  });
}
