import type { Db } from '../db/connection.js';
import { nowIso } from '../lib/time.js';
import { HttpError } from '../lib/errors.js';
import * as wo from './workOrders.js';

/**
 * Preventive maintenance. Calendar and meter triggers, generated by a nightly job
 * in the host process. If the host was off, it catches up on the next boot rather
 * than skipping the day.
 */
export interface PpmSchedule {
  id: string; property_id: string; name: string; scope_type: 'asset' | 'category' | 'location';
  asset_id: string | null; asset_category_id: string | null; location_id: string | null;
  trigger_type: 'calendar' | 'meter';
  interval_value: number; interval_unit: string; lead_days: number;
  checklist_template_id: string | null; default_team_id: string | null; default_trade: string | null;
  priority: 'P1' | 'P2' | 'P3' | 'P4'; estimated_minutes: number | null;
  last_completed_at: string | null; last_meter_at_completion: number | null;
  next_due_at: string | null; next_due_meter: number | null;
  auto_generate: number; is_active: number;
}

const MS = { day: 86_400_000, week: 604_800_000 };

export function addInterval(from: string, value: number, unit: string): string {
  const d = new Date(from);
  switch (unit) {
    case 'day':   return new Date(d.getTime() + value * MS.day).toISOString();
    case 'week':  return new Date(d.getTime() + value * MS.week).toISOString();
    case 'month': { const n = new Date(d); n.setUTCMonth(n.getUTCMonth() + value); return n.toISOString(); }
    case 'year':  { const n = new Date(d); n.setUTCFullYear(n.getUTCFullYear() + value); return n.toISOString(); }
    default: throw new HttpError(400, 'bad_interval', `"${unit}" is not a calendar interval.`);
  }
}

function targetAssets(db: Db, s: PpmSchedule): { id: string; name: string; current_meter: number | null }[] {
  if (s.scope_type === 'asset') {
    return db.prepare('SELECT id, name, current_meter FROM assets WHERE id = ? AND is_active = 1')
      .all(s.asset_id) as never;
  }
  if (s.scope_type === 'category') {
    return db.prepare(
      `SELECT id, name, current_meter FROM assets
        WHERE category_id = ? AND is_active = 1 AND status <> 'decommissioned'`
    ).all(s.asset_category_id) as never;
  }
  return db.prepare(
    `SELECT id, name, current_meter FROM assets
      WHERE location_id = ? AND is_active = 1 AND status <> 'decommissioned'`
  ).all(s.location_id) as never;
}

function alreadyOpen(db: Db, scheduleId: string, assetId: string): boolean {
  return !!db.prepare(
    `SELECT 1 FROM work_orders WHERE ppm_schedule_id = ? AND asset_id = ?
      AND status NOT IN ('verified','closed','cancelled') LIMIT 1`
  ).get(scheduleId, assetId);
}

export interface GenerateResult { considered: number; created: { ref: string; schedule: string; asset: string }[] }

export function generateDue(
  db: Db, ctx: wo.Ctx, at: string = nowIso()
): GenerateResult {
  const schedules = db.prepare(
    'SELECT * FROM ppm_schedules WHERE property_id = ? AND is_active = 1 AND auto_generate = 1'
  ).all(ctx.propertyId) as PpmSchedule[];

  const created: GenerateResult['created'] = [];

  for (const s of schedules) {
    const horizon = new Date(new Date(at).getTime() + s.lead_days * MS.day).toISOString();

    for (const asset of targetAssets(db, s)) {
      let due = false;
      let dueAt: string | undefined;

      if (s.trigger_type === 'calendar') {
        if (s.next_due_at && s.next_due_at <= horizon) { due = true; dueAt = s.next_due_at; }
      } else {
        const meter = asset.current_meter ?? 0;
        if (s.next_due_meter != null && meter >= s.next_due_meter) {
          due = true;
          dueAt = new Date(new Date(at).getTime() + 7 * MS.day).toISOString();
        }
      }
      if (!due || alreadyOpen(db, s.id, asset.id)) continue;

      const job = wo.create(db, ctx, {
        title: `${s.name} — ${asset.name}`,
        description: s.trigger_type === 'meter'
          ? `Meter-triggered service at ${asset.current_meter ?? 0} ${s.interval_unit}.`
          : `Scheduled every ${s.interval_value} ${s.interval_unit}(s).`,
        trade: s.default_trade ?? undefined,
        priority: s.priority,
        source: 'ppm',
        assetId: asset.id,
        ppmScheduleId: s.id,
        dueAt,
      });
      created.push({ ref: job.ref, schedule: s.name, asset: asset.name });
    }
  }
  return { considered: schedules.length, created };
}

/**
 * Recompute the next due date from the DUE date, not the completion date — otherwise
 * schedules drift later every cycle until the annual service happens in December.
 */
export function onWorkOrderVerified(db: Db, propertyId: string, workOrderId: string, at: string = nowIso()): void {
  const job = db.prepare(
    'SELECT ppm_schedule_id, asset_id, due_at FROM work_orders WHERE id = ? AND property_id = ?'
  ).get(workOrderId, propertyId) as
    { ppm_schedule_id: string | null; asset_id: string | null; due_at: string | null } | undefined;
  if (!job?.ppm_schedule_id) return;

  const s = db.prepare('SELECT * FROM ppm_schedules WHERE id = ?').get(job.ppm_schedule_id) as
    PpmSchedule | undefined;
  if (!s) return;

  if (s.trigger_type === 'calendar') {
    const anchor = job.due_at ?? s.next_due_at ?? at;
    let next = addInterval(anchor, s.interval_value, s.interval_unit);
    // If the job was completed very late, roll forward until the next due date is ahead.
    let guard = 0;
    while (next <= at && guard++ < 500) next = addInterval(next, s.interval_value, s.interval_unit);
    db.prepare(
      'UPDATE ppm_schedules SET last_completed_at = ?, next_due_at = ?, updated_at = ? WHERE id = ?'
    ).run(at, next, at, s.id);
  } else {
    const meter = job.asset_id
      ? (db.prepare('SELECT current_meter FROM assets WHERE id = ?').get(job.asset_id) as
          { current_meter: number | null } | undefined)?.current_meter ?? 0
      : 0;
    db.prepare(
      `UPDATE ppm_schedules SET last_completed_at = ?, last_meter_at_completion = ?,
        next_due_meter = ?, updated_at = ? WHERE id = ?`
    ).run(at, meter, meter + s.interval_value, at, s.id);
  }
}

export interface Compliance {
  generated: number; onTime: number; late: number; open: number; overdue: number;
  judged: number; compliancePct: number | null;
}

/**
 * A job that has been raised but is not due for another three weeks is not a failure, so
 * it stays out of the denominator entirely. Counting it as one — which dividing by every
 * job raised does — reports 0% on a property where nothing is actually late, and a
 * measure that cries wolf on day one is a measure nobody looks at again.
 *
 * Judged = done, plus open-and-already-overdue. An overdue job counts against you the
 * moment it is late, not when somebody finally closes it. With nothing judged yet the
 * percentage is null rather than zero: unknown and bad are different answers.
 */
export function compliance(db: Db, propertyId: string, from: string, to: string,
                           at: string = nowIso()): Compliance {
  const rows = db.prepare(
    `SELECT status, due_at, completed_at FROM work_orders
      WHERE property_id = ? AND source = 'ppm' AND reported_at BETWEEN ? AND ?`
  ).all(propertyId, from, to) as { status: string; due_at: string | null; completed_at: string | null }[];

  let onTime = 0, late = 0, open = 0, overdue = 0;
  for (const r of rows) {
    const done = ['completed', 'verified', 'closed'].includes(r.status);
    if (!done) {
      open++;
      if (r.due_at && r.due_at < at) overdue++;
      continue;
    }
    if (r.due_at && r.completed_at && r.completed_at <= r.due_at) onTime++;
    else late++;
  }
  const judged = onTime + late + overdue;
  return {
    generated: rows.length, onTime, late, open, overdue, judged,
    compliancePct: judged ? Math.round((onTime / judged) * 1000) / 10 : null,
  };
}
